# Generated by Django 3.2 on 2023-05-28 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_confirmationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(default=uuid.UUID('ee281dbc-9095-4789-b9a1-375766a2719b'), max_length=6),
        ),
    ]
